config/routes.rb
Blog::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
root :to =>'posts#index'
  resources :posts do
    resources :comments
  end

  delete  'likes/:resource_name/:resource_id' => "likes#destroy", :as => 'unlike'
  post    'likes/:resource_name/:resource_id' => "likes#create", :as => 'like'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #attr_accessible :body, :post_id
  include Likeable
  validates_presence_of :body
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  #attr_accessible :body, :title
  include Likeable
  validates_presence_of :body, :title
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  include Likeable::UserMethods
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id ])
    @comment = @post.comments.create!(comment_params)
     respond_to do |format|
       format.html {redirect_to @post}
       format.js
     end
  end


  private

  def comment_params
    params.require(:comment).permit(:post_id, :body, :user_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @target = Likeable.find_by_resource_id(params[:resource_name], params[:resource_id])
    current_user.like!(@target)
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
  end
  end

  def destroy
    @target = Likeable.find_by_resource_id(params[:resource_name], params[:resource_id])
    current_user.unlike!(@target)
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController



  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.xml { render xml: @posts }
      format.atom
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end


  private
  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def like_link_for(target)
     link_to  like_path(:resource_id => target.id,:resource_name => target.class), :method => :post, :remote => true do
                 image_tag "like-64x64.png", :size => "20", :alt => "Like", :title => "Like"
     end
  end

  def unlike_link_for(target)
     link_to  unlike_path(:resource_id => target.id,:resource_name => target.class), :method => :delete, :remote => true  do
                 image_tag "unlike-64x64.png", :size => "20", :alt => "Unlike", :title => "Unlike"
     end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
	<%= content_tag_for(:li, comment, :class => 'list-group-item') do %>
        <div class="pull-right">
          <% if user_signed_in? %>
              <% if  current_user.likes?(comment) %>
                  <%= unlike_link_for comment %>
              <% else %>
                  <%= like_link_for comment %>
              <%end%>
          <% else %>
              <%= link_to new_user_session_path do  %>
                  <%=  image_tag "like-64x64.png", :size => "20", :alt => "Like", :title => "Like" %>
              <% end %>
          <% end %>
          <span class="badge"><%= comment.like_count %></span>
        </div>
	<p>
      <em>
		 <strong>Posted <%= time_ago_in_words(comment.created_at) %> ago by <%= User.find(comment.user_id).email%></strong>
      </em>
      <br/>
		<%= comment.body.html_safe %>

	</p>
	<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="field">
      <%= f.hidden_field :user_id, :value => current_user.id  %>
    </div>
  <div class="field">
    <%= f.label :post_id %><br />
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body , :class => "form-control"%>
  </div>
  <div class="actions">
    <%= f.submit :class=>"btn" %>
  </div>
<% end %>

app/views/comments/create.js.erb
// Created by kolenko_s on 12.08.14.
//=require JQueryColor
comment = '<%= escape_javascript render :partial => @comment %>';
$("#comments").append(comment);
$("#comments div:last-child").animate( {backgroundColor: 'white'}, 1000);
$('#cke_comment_body .cke_wysiwyg_frame').contents().find('body').text('');

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Post</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.post_id %></td>
    <td><%= comment.body %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Blog", posts_path, :class => "navbar-brand" %>
        <% if user_signed_in? %>
            <div class="pull-right">

              <strong><%= current_user.email %></strong><br />
              <%= link_to  "Sign out", destroy_user_session_path,:method => :delete, :class => "btn btn-primary pull-right" %>
            </div>
        <%else%>
            <%= link_to "Sign in" ,new_user_session_path, :class=>"btn btn-success pull-right" %>
        <%end%>
      </div>
    </div>

    <div class="container">
      <div class="row">
          <%= bootstrap_flash %>
          <%= yield %>
          </div>
        </div>


  </body>
</html>

app/views/likes/create.js.erb
var like_div =  $('#<%= params[:resource_name].downcase%>_<%= params[:resource_id] %>  .pull-right');
$(like_div).find('span').text('<%= @target.like_count %>');
$(like_div).find('a').replaceWith('<%= unlike_link_for(@target) %>');

app/views/likes/destroy.js.erb
var like_div =  $('#<%= params[:resource_name].downcase%>_<%= params[:resource_id] %> .pull-right');
$(like_div).find('span').text('<%= @target.like_count %>');
$(like_div).find('a').replaceWith('<%= like_link_for(@target) %>');

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id  %>
   </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title , :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :class => "form-control ckeditor" %>
  </div> <br />
  <div class="actions">
    <%= f.submit :class => "btn" %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<%= div_for post, :class => 'panel panel-default'  do %>
    <%= div_for post, :class => 'panel-heading'  do %>
        <div class="pull-right">
        <% if user_signed_in? %>
        <% if  current_user.likes?(post) %>
            <%= unlike_link_for post %>
        <% else %>
             <%= like_link_for post %>
        <%end%>
        <% else %>
            <%= link_to new_user_session_path do  %>
              <%=  image_tag "like-64x64.png", :size => "20", :alt => "Like", :title => "Like" %>
        <% end %>
        <% end %>
        <span class="badge"><%= post.like_count %></span>
        </div>
	<h2><%= link_to_unless_current post.title, post %></h2>
    <small>Created by <%= User.find(post.user_id).email  %> at <%= time_ago_in_words(post.created_at) %> ago </small>
<% end %>
    <%= div_for post, :class => 'panel-body'  do %>
<%= post.body.html_safe %>
    <% end %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<%= render :partial => @posts %>

<%= link_to 'New Post', new_post_path, :class => 'btn btn-primary' %>

app/views/posts/new.html.erb
<% if user_signed_in? %>
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
<% else %>
    <p> <h2>
      <%= link_to "Sign in", new_user_session_path %> or <%= link_to "Sign up", new_user_registration_path %>
      to add new post</h2>
    </p>
<% end %>

app/views/posts/show.html.erb
<%= render :partial => @post %>
<% if user_signed_in? && current_user.id == @post.user_id %>
<p>
	<%= link_to 'Edit', edit_post_path(@post) %> |
	<%= link_to 'Delete',@post, :confirm => "Are you sure?", :method => :delete %>
</p>
<% end %>
<p><%= link_to 'See all posts', posts_path %></p>
<h2>Comments</h2>
<ul id='comments' class="list-group">
	<%= render :partial => @post.comments %>
</ul>
<% if user_signed_in? %>
<%=  form_for  [@post, Comment.new], :remote => true do |f| %>
	    <p>
         <%= f.hidden_field :user_id, :value => current_user.id %>
		<%=  f.label  :body, 'New comment' %> <br />
		<%= f.text_area  :body , :class => 'form-control ckeditor'%>
	</p>
	<p><%= f.submit 'Add comment', :class=>"btn" %></p>
<% end %>
<% else %>
    <p> <h3>
  <%= link_to "Sign in", new_user_session_path %> or <%= link_to "Sign up", new_user_registration_path %>
  to add comment</h3>
    </p>
<% end %>